### Installation building a development image from build.
FROM soprun/sandbox-main-php:base AS dev

### Environment variables
ENV COMPOSER_HOME="/composer"
ENV COMPOSER_CACHE_DIR="${COMPOSER_HOME}/cache"
ENV COMPOSER_MEMORY_LIMIT="-1"
ENV COMPOSER_ALLOW_SUPERUSER="1"

ENV PATH="${PATH}:${COMPOSER_HOME}/vendor/bin"

COPY --from=soprun/sandbox-main-php:composer /composer /composer
COPY --from=soprun/sandbox-main-php:composer /usr/bin/composer /usr/bin/composer

RUN set -eux; \
    # Use the default development configuration
    mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"; \
    # Install application dependencies
    composer install \
      --no-progress \
      --no-scripts \
      --no-interaction \
      --prefer-dist \
      --optimize-autoloader \
      --classmap-authoritative \
      --profile
