### Installation base container
FROM php:7.4-fpm-alpine AS builder

ENV APP_ENV="dev"
ENV APP_DEBUG="1"

### Installation building a production image from build.
FROM builder AS prod

ENV APP_ENV="prod"
ENV APP_DEBUG="0"

### Installation building a development image from build.
FROM builder AS dev
