#!/bin/bash

readonly name="sandbox-php-lol"
readonly tag_latest="latest"
readonly tag_builder="builder"
readonly tag_development="dev"
readonly tag_production="prod"

set -x

docker builder build \
    --file "./docker/php/Dockerfile" \
    --target prod \
    .

#docker build \
#    --file "./docker/php/Dockerfile" \
#    --target "${tag_development}" \
#    --tag "${name}:${tag_development}" \
#    .

#docker run --name "${name}-${tag_production}" "${name}:${tag_production}"
#docker run --name "${name}-${tag_development}" "${name}:${tag_development}"
