#!/bin/bash

set -ex

# Current working directory
CWD="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"

source "${CWD}/.env"

# shellcheck source=./docker/bin/common.sh
#source "${CWD}/bin/common.sh"

# docker context create sandbox-docker
# docker buildx create --use --name mybuild node-amd64

# Deploying to GCP

# Tags
# readonly tag_latest="latest"
readonly tag_build="build"
readonly tag_dev="dev"
readonly tag_prod="prod"

#declare -a repositories=(
#    "php_fpm::${IMAGE_PHP_FPM}"
#    "php_cli::${IMAGE_PHP_CLI}"
#    "php_workspace::${IMAGE_PHP_WORKSPACE}"
#)

#for index in "${repositories[@]}"; do
#    service_name="${index%%::*}"
#    repository_name="${index##*::}"
#
#    # echo "$service_name -> $repository_name"
#done

#declare -a docker_compose_files=(
#    "/docker/docker-compose.yml"
#)

# docker build --platform=local -o . git://github.com/docker/buildx
# UN --mount=target=. --mount=target=/root/.cache,type=cache   --mount=target=/go/pkg/mod,type=cache   --mount=sou

# todo: add--rm & --force-rm

docker build \
    --file "./docker/php/Dockerfile" \
    --tag "${IMAGE_PHP}:composer" \
    --target "composer" \
    .

docker build \
    --file "${CWD}/php/Dockerfile" \
    --tag "${IMAGE_PHP}:build" \
    --target "build" \
    --label "project.version=$(git describe --tags --abbrev=0)" \
    --label "project.branch=$(git rev-parse --abbrev-ref HEAD)" \
    --label "project.commit=$(git rev-parse HEAD)" \
    .

docker build \
    --file "${CWD}/php/Dockerfile.dev" \
    --tag "${IMAGE_PHP}:dev" \
    --target "dev" \
    .

docker build \
    --file "./docker/php/Dockerfile.prod" \
    --tag "${IMAGE_PHP}:prod" \
    --target "prod" \
    .

docker build \
    --file "./docker/php/Dockerfile.workspace" \
    --tag "${IMAGE_PHP}:workspace" \
    --target "workspace" \
    .

#docker push "${IMAGE_PHP}:dev"
#docker push "${IMAGE_PHP}:prod"
#docker push "${IMAGE_PHP}:workspace"

#docker push "${IMAGE_PHP_FPM}"
#docker push "${IMAGE_PHP_CLI}"
#docker push "${IMAGE_PHP_WORKSPACE}"
