#!/bin/bash

# git flow feature start

git flow release start 0.0.1

git flow release finish 0.1.5

# release finish

git commit -S -m "signed commit..."

git push
git push origin --tags --signed=yes


git flow release finish -m "Your message" "release1"
git checkout master
git push --all origin