#!/bin/bash

#docker build \
#  --build-arg APP_ENV=prod \
#  --build-arg APP_DEBUG=1 \
#  --file ./docker/php/Dockerfile \
#  --tag "soprun/sandbox-php:latest" \
#  .
#
#
#
#docker rm php

#docker stop php >/dev/null 2>&1
#docker rm php >/dev/null 2>&1

#exit 0

#docker-compose \
#  --file ./docker-compose.yml \
#  --env-file ./.env \
#  --env-file ./docker/environment.yaml \
#  up -d --build php
#
#
#exit 0


vault server -dev