#!/bin/bash

docker builder build \
    --file "./docker/php/Dockerfile" \
    --tag "soprun/sandbox-main-php-fpm:composer" \
    --target "composer" \
    .

docker builder build \
    --file "./docker/php/Dockerfile" \
    --tag "soprun/sandbox-main-php-fpm:build" \
    --target "build" \
    .

docker builder build \
    --file "./docker/php/Dockerfile.dev" \
    --tag "soprun/sandbox-main-php-fpm:dev" \
    --target "dev" \
    .

docker builder build \
    --file "./docker/php/Dockerfile.prod" \
    --tag "soprun/sandbox-main-php-fpm:prod" \
    --target "prod" \
    .

#docker builder build \
#    --file "./docker/php/Dockerfile" \
#    --target "composer" \
#    .
