version: "3.8"

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  redis:
    name: redis
    driver: ${VOLUMES_DRIVER}

services:
  redis:
    image: redis:${REDIS_VERSION}-alpine
    container_name: redis
    ports:
      - "${REDIS_PORT_HOST}:6379"
    volumes:
      - redis:/data
    networks:
      - backend