version: "3"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../app/public:/app/public:ro
    depends_on:
      - php
    ports:
      - "80:80"

  php:
    image: php-docker/php-fpm
    container_name: php
    restart: on-failure
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ../app:/app:rw,delegated
    # Allows to debug php script run inside PHP container
    environment:
      PHP_IDE_CONFIG: serverName=es.local

