version: "3.4"

volumes:
  #  default:
  #    driver: local
  # for persistence between restarts
  postgres_data: { }

#networks:
#  frontend_tier:
#    driver: bridge
#  backend_tier:
#    driver: bridge

x-logging:
  &default_logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

x-php:
  &default_php
  env_file:
    - .env
  volumes:
    - ../app:/app:rw,cached
    - ${COMPOSER_CACHE_DIR}:/composer/cache:rw,cached
  depends_on:
    - postgres
    - redis

services:
  nginx:
    build:
      dockerfile: ./docker/nginx/Dockerfile
      context: ..
    container_name: nginx
    <<: *default_logging
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php

  php: # php_worker
    image: soprun/sandbox-php:dev
    build:
      dockerfile: ./docker/php/Dockerfile
      context: ..
      target: dev
    container_name: php
    privileged: true
    <<: *default_logging
    <<: *default_php

  # php_workspace:
  #   build:
  #     dockerfile: ./docker/php-cli/Dockerfile
  #     context: ..
  #   container_name: php_workspace
  #   <<: *default_logging
  #   <<: *default_php

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USERNAME
      - POSTGRES_PASSWORD
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    container_name: redis
    ports: [ 6379 ]
