version: "3"

volumes:
  # for persistence between restarts
  postgres:
    name: postgres
    driver: local

services:
  php:
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    hostname: "$POSTGRES_HOST"
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USERNAME
      - POSTGRES_PASSWORD
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
