version: "3.4"

#volumes:
#  default:
#    driver: local

networks:
  frontend_tier:
    driver: bridge
  backend_tier:
    driver: bridge

x-logging:
  &default_logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

x-php:
  &default_php
  env_file:
    - .env
  volumes:
    - ../app:/app:rw,consistent
    - ${COMPOSER_CACHE_DIR}:/composer/cache:rw,cached
  networks:
    - backend_tier
  depends_on:
    - postgres
    - redis

services:
  nginx:
    build:
      dockerfile: ./docker/nginx/Dockerfile
      context: ..
    container_name: nginx
    <<: *default_logging
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend_tier
      - backend_tier
    depends_on:
      - php

  php: # php_worker
    build:
      dockerfile: ./docker/php/Dockerfile
      context: ..
    container_name: php
    privileged: true
    <<: *default_logging
    <<: *default_php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  # php_workspace:
  #   build:
  #     dockerfile: ./docker/php-cli/Dockerfile
  #     context: ..
  #   container_name: php_workspace
  #   <<: *default_logging
  #   <<: *default_php

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USERNAME
      - POSTGRES_PASSWORD
    ports: [ 5432 ]
    networks:
      - backend_tier

  redis:
    image: redis:6-alpine
    container_name: redis
    ports: [ 6379 ]
    networks:
      - backend_tier
