#!/bin/sh

set -ex

# https://github.com/paslandau/docker-php-tutorial/blob/part_3_structuring-the-docker-setup-for-php-projects/.docker/.shared/scripts/create_user.sh

APP_USER="${1:-www-data}"
APP_USER_ID="${3:-1000}"

APP_GROUP="${2:-www-data}"
APP_GROUP_ID="${4:-1000}"

echo "app_user: $APP_USER"
echo "app_user_id: $APP_USER_ID"
echo "app_group: $APP_GROUP"
echo "app_group_id: $APP_GROUP_ID"

exit 0
