# https://www.docker.com/blog/docker-github-actions/
# https://github.com/metcalfc/docker-action-examples/tree/main/.github/workflows

name: Docker build image
on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - develop
    # paths:
    #   - '.github/**'
    #   - 'docker/**'
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  # Run tests for any PRs.
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # GITHUB_CONTEXT: ${{ toJson(github) }}

  IMAGE_PHP_NAME: soprun/docker-project-php
  IMAGE_PHP_FILE: ./docker/php/Dockerfile
  IMAGE_NGINX_NAME: soprun/docker-project-nginx
  IMAGE_NGINX_FILE: ./docker/nginx/Dockerfile

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ env.IMAGE_PHP_FILE }}
          push: true
          tags: |
            ${{ env.IMAGE_PHP_NAME }}:latest
