name: Docker build CI

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - develop
    # paths:
    #   - '.github/**'
    #   - 'docker/**'
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  # Run tests for any PRs.
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_CONTEXT: ${{ toJson(github) }}

  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

  PHP_IMAGE_NAME: soprun/docker-project-php
  PHP_IMAGE_FILE: ./docker/php/Dockerfile

  NGINX_IMAGE_NAME: soprun/docker-project-nginx
  NGINX_IMAGE_FILE: ./docker/nginx/Dockerfile

  PROJECT_NAME: docker-project
  PROJECT_RELEASE: ""

jobs:
  build:
    name: Build stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup release
        id: release
        run: |
          RELEASE_NAME=$(printf "release-%s\n" "$(date +'%Y-%m-%d')")
          echo "::set-output name=RELEASE_NAME::$RELEASE_NAME"

          # Strip git ref prefix from version
          RELEASE_TAG=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && $RELEASE_TAG=$(echo $RELEASE_TAG | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$RELEASE_TAG" == "master" ] && RELEASE_TAG=latest

          echo "::set-output name=RELEASE_TAG::$RELEASE_TAG"
          # latest, develop, v1.1.2

      # - name: Run build script
      #   run: ./docker/build
      #   shell: bash

      - name: Build Docker image
        id: build
        run: |
          RELEASE_NAME=${{ steps.release.outputs.RELEASE_NAME }}
          TAG=${{ steps.release.outputs.RELEASE_TAG }}"

          echo "RELEASE_NAME: $RELEASE_NAME"
          echo "RELEASE_TAG: $TAG"

          # docker build . \
          # --file "$PHP_IMAGE_FILE" \
          # --tag "$PHP_IMAGE_NAME:dev-$VERSION" \
          # --target "$APP_ENV" \
          # --label "project.env=$APP_ENV" \
          # --label "project.version=$VERSION" \
          # --label "project.commit_sha=$COMMIT_SHA"

  test:
    needs: build
    name: Test stage
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
    steps:
      - run: echo "The test stage..."

  release:
    needs: test
    name: Release stage
    if: contains(github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - run: echo "The release stage..."

  deploy_prod:
    needs: release
    name: Deploy stage
    if: contains(github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy to production server"