# https://www.docker.com/blog/docker-github-actions/
# https://github.com/metcalfc/docker-action-examples/tree/main/.github/workflows

name: Docker build image

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
    paths:
      - '.github/**'
      - 'docker/**'
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # GITHUB_CONTEXT: ${{ toJson(github) }}

  IMAGE_PHP_NAME: soprun/docker-project-php
  IMAGE_PHP_FILE: ./docker/php/Dockerfile
  IMAGE_NGINX_NAME: soprun/docker-project-nginx
  IMAGE_NGINX_FILE: ./docker/nginx/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Setup build
        if: success()
        id: setup
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo ::set-output name=version::${VERSION}

          echo "IMAGE_PHP_NAME: ${{ env.IMAGE_PHP_NAME }}"
          echo "IMAGE_PHP_FILE: ${{ env.IMAGE_PHP_FILE }}"
          echo "${{ env.IMAGE_PHP_NAME }}:dev-${{ steps.setup.outputs.version }}"

      - name: "Build: PHP dev"
        if: success()
        id: build_php_dev
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ env.IMAGE_PHP_FILE }}
          push: true
          target: dev
          tags: |
            ${{ env.IMAGE_PHP_NAME }}:${{ steps.setup.outputs.version }}-dev
          cache-from: |
            ${{ env.IMAGE_PHP_NAME }}:cache

      - name: "Build: PHP prod"
        if: success()
        id: build_php_prod
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ env.IMAGE_PHP_FILE }}
          push: true
          target: prod
          tags: |
            ${{ env.IMAGE_PHP_NAME }}:${{ steps.setup.outputs.version }}
          cache-from: |
            ${{ env.IMAGE_PHP_NAME }}:cache

      - name: "Build: Nginx dev"
        if: success()
        id: build_nginx_dev
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ env.IMAGE_NGINX_FILE }}
          push: true
          target: dev
          tags: |
            ${{ env.IMAGE_NGINX_NAME }}:${{ steps.setup.outputs.version }}-dev
          cache-from: |
            ${{ env.IMAGE_NGINX_NAME }}:cache

      - name: "Build: Nginx prod"
        if: success()
        id: build_nginx_prod
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ env.IMAGE_NGINX_FILE }}
          push: true
          target: prod
          tags: |
            ${{ env.IMAGE_NGINX_NAME }}:${{ steps.setup.outputs.version }}
          cache-from: |
            ${{ env.IMAGE_NGINX_NAME }}:cache

      - name: Run Snyk to check Docker image for vulnerabilities
        # Snyk can be used to break the build when it detects vulnerabilities.
        # In this case we want to upload the issues to GitHub Code Scanning
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          # In order to use the Snyk Action you will need to have a Snyk API token.
          # More details in https://github.com/snyk/actions#getting-your-snyk-token
          # or you can signup for free at https://snyk.io/login
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.IMAGE_PHP_NAME }}:latest
          args: --file=${{ env.IMAGE_PHP_FILE }}

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif